name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test:ci
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          persist-credentials: false
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "coaster-ranker-api"
          heroku_email: "ajdhefley@gmail.com"
          